version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Rome"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 2

  - package-ecosystem: "npm"
    directory: "/OmniRID-Desktop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Rome"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 2

  - package-ecosystem: "cargo"
    directory: "/OmniRID"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Rome"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 2
